### ISSUE TITLE
Optimize API-Key configuration

### ISSUE THREAD

**Issue by fenepedia** [fenepedia/contao-er24-rechtstexte#10]
Um den Multi-Domain-Support zu nutzen, muss es weiterhin über den Website-Root konfigurierbar sein. Allerdings wäre vielleicht eine Option “Verwende den gleichen eRecht-Client wie bei der Fallbackseite", hilfreich?

Hm, I guess we should remove 

https://github.com/fenepedia/contao-er24-rechtstexte/blob/0ac995f1e052c1d643981d738801f9b0d412a963/contao/dca/tl_page.php#L50

if it really works with only the fallback root.

_Originally posted by @fritzmg in https://github.com/fenepedia/contao-er24-rechtstexte/issues/9#issuecomment-1219115852_

**Comment by fritzmg** [comment]
Fixed in [dde0717](https://github.com/fenepedia/contao-er24-rechtstexte/commit/dde07179e2059fe06206517f393bc1a3a5a922c7)

**Comment by fenepedia** [comment]
Thx @fritzmg
