### ISSUE TITLE
Mehrsprachigkeit / MultiDomain

### ISSUE THREAD

**Issue by katgirl** [fenepedia/contao-er24-rechtstexte#12]
Wir haben bei unseren mehrsprachigen Domains das Phänomen, das wir den API-Key nur in eine der Sprachen einfügen können. Zudem scheint die Sprache auch nicht berücksichtigt zu werden.

**Comment by fritzmg** [comment]
Der API Key wird nur im Fallback eingetragen. Welche Sprachen habt ihr in den Website Roots eingetragen?

**Comment by katgirl** [comment]
Danke, klappt. sollte dann aber mit in die Doku, denn das war nicht selbsterklärend ;-)

**Comment by fritzmg** [comment]
> sollte dann aber mit in die Doku

In der Doku steht folgendes:

> In Contao den API-Schlüssel beim **Fallback-Startpunkt** der Website hinterlegen

**Comment by katgirl** [comment]
Nur leider nicht in der die Redakteure lesen ;-)

https://www.fenepedia.de/contao-er24-rechtstexte

**Comment by fenepedia** [comment]
Ich habs in den FAQs drin. Als letzter Eintrag.
Vielleicht nehme ich es als eigenen Punkt in die Doku auf. Ich muss die Doku sowieso noch für den neuen Projektmanager etwas anpassen.

**Comment by fenepedia** [comment]
Wir haben den Hinweis für die Mehrsprachigkeit als eigenen Eintrag hinzugefügt und im Inhaltsverzeichnis verlinkt.
https://www.fenepedia.de/contao-er24-rechtstexte
