### ISSUE TITLE
Wrong evaluated email insert tag inside "Name und Anschrift der zuständigen Kammer" textarea

### ISSUE THREAD

**Issue by Matheoz-sys** [fenepedia/contao-er24-rechtstexte#14]
I've found weird bug with automatically parsing e-mails. 

The bug appeared inside "Aufsichts­behörde, Berufs­bezeichnung" in the "Name und Anschrift der zuständigen Kammer" textarea after entering an email.

End of insert tags are placed exactly inside following `br` tag  `<b|here|r />` , causing email not to be parsed into html tag.

![image](https://user-images.githubusercontent.com/70640336/222662681-0b61cd6f-67a5-4310-bb51-8c64faa12ff6.png)

Coming from Back-End:

![image](https://user-images.githubusercontent.com/70640336/222662425-d4ec5ee6-0277-454a-8ecf-983f061384f0.png)

As i checked value on textarea at erecht24, the line with e-mail seems to be written correctly - `E-Mail: email@example.com\n`

**Comment by fenepedia** [comment]
@fritzmg @etlam Can you someone check this?

**Comment by fritzmg** [comment]
What is the original HTML code?

**Comment by fritzmg** [comment]
I have updated the email regex in https://github.com/fenepedia/contao-er24-rechtstexte/commit/2fbd67e9a5a65b7a1e5bd885797cd879f6ce5133 - please try `dev-main`.

**Comment by etlam** [comment]
I can not help with the original html code, as i am not able to find the project this snippet belongs to.

**Comment by Matheoz-sys** [comment]
New implementation works a bit better,  but issue still persists.
Here you can view current regex output: https://regex101.com/r/JrY09P/1

![image](https://user-images.githubusercontent.com/70640336/222720657-32a78f75-5140-400c-82db-d0167a20c17e.png)

Client website: https://www.ratajak-steuerberatung.de/impressum

**Comment by etlam** [comment]
```html
<h2>Berufsbezeichnung und berufsrechtliche Regelungen</h2>
<p>Berufsbezeichnung:<br />
Steuerberater</p>
<p>Zust&auml;ndige Kammer:<br />
Steuerberaterkammer M&uuml;nchen<br />
K&ouml;rperschaft des &ouml;ffentlichen Rechts<br />
Nederlinger Str. 9<br />
80638 M&uuml;nchen<br />
Deutschland<br />
Telefon: +49(0)89 / 15 79 02-0<br />
Fax: +49(0)89 / 15 79 02-19<br />
E-Mail: info@stbk-muc.de<br />
www.stbk-muc.de</p>
```

**Comment by fritzmg** [comment]
Try again with the current `dev-main`. However, there will still be edge cases. e.g. `<br>foobar@example.com` won't work.

**Comment by Matheoz-sys** [comment]
I've currently another problem. I'm not sure if the Regex causing it, or there is an issue with eRecht itself. I've entered totally another mail inside, and tried to sync legal texts. eRecht said, that my exports were successful, but new imprint wasn't imported.

I've already tried clearing the cache, and even creating new eRecht key, and connecting it with website(came new secret and client Id), but there is no change in DB/Frontend. I also haven't found anything in logs.

**Comment by etlam** [comment]
> I've currently another problem. I'm not sure if the Regex causing it, or there is an issue with eRecht itself. I've entered totally another mail inside, and tried to sync legal texts. eRecht said, that my exports were successful, but new imprint wasn't imported.
> 
> I've already tried clearing the cache, and even creating new eRecht key, and connecting it with website(came new secret and client Id), but there is no change in DB/Frontend. I also haven't found anything in logs.

Same website as above? Then I will have a look at the logs for Rechtstexte API.

**Comment by etlam** [comment]
The Contao receives the push from eRecht24 Rechtstexte API and answers with http status 200 and message "OK".

Now the Contao should flush the corresponding cache tag for the legal notice and start  a request to the API as soon as the page gets displayed.  
But I can not see a request belonging to the website to fetch the new legal notice.

Maybe @fritzmg can help, seems to me like a cache problem with Contao.

**Comment by fritzmg** [comment]
The request is made here:

https://github.com/fenepedia/contao-er24-rechtstexte/blob/48952a06ba5ad72faf003f29b929192ac47b5ffd/src/Controller/ContentElement/LegalTextElementController.php#L118

@Matheoz-sys does it work if you clear the eRecht24 cache via Contao's system maintenance?

**Comment by Matheoz-sys** [comment]
Just as before, there was no change after clearing cache, but at least I have became this warning in debug mode

![image](https://user-images.githubusercontent.com/70640336/223079329-4f95fbf7-ac69-437e-9f8a-a9813e09d0ef.png)

**Comment by fritzmg** [comment]
@Matheoz-sys I think https://github.com/fenepedia/contao-er24-rechtstexte/commit/8203806654725692c1f4180188daf5168917d980 should fix that. Please update `dev-main` again.

**Comment by Matheoz-sys** [comment]
Yes, the new imprint was imported correctly. Thanks for help. 👍
