### ISSUE TITLE
Hinweis in Systemlog wenn kein Text vorhanden ist

### ISSUE THREAD

**Issue by fenepedia** [fenepedia/contao-er24-rechtstexte#2]
Wenn ein Text-Typ nicht vorhanden ist, dann bekomme ich keinen Hinweis. Es wäre vielleicht hilfreich, wenn eine Meldung im System-Log erscheint.

Beispiel: `Zum Rechtstext-Typ XXX konnten keine Daten gefunden/abgerufen werden.`

**Comment by fritzmg** [comment]
Statt einer Systemlog Nachricht habe ich es nun so implementiert, dass dieser Hinweis einfach im Backend angezeigt wird, wenn keine Daten vorhanden sind.
