### ISSUE TITLE
Fallback wenn kein API-Key mehr vorhanden?

### ISSUE THREAD

**Issue by fenepedia** [fenepedia/contao-er24-rechtstexte#3]
Ich frage mich gerade, ob es sinnvoll wären, dass es eine Fallbacklösung gibt.

### Problem
Ich lösche bei eRecht den API-Key. Wenn das der Website-Admin nicht mitbekommt und irgendwann den Cache über die Systemsteuerung löscht, dann gibt es plötzlich keine Texte mehr auf der Website. Das wäre ggf. sehr fatal.
Evtl. können wir die Texte erst invalidieren, wenn vorher geprüft wird, ob noch eine Verbindung zu eRecht24 besteht.
Oder hast du andere Ideen?

**Comment by fenepedia** [comment]
Ich finde das so halt schon riskant. Nehmen wir an die Agentur die dich betreut löscht den API-Key. Dann hast du von heute auf morgen keine Texte mehr und kannst nicht mal auf die alten Daten zugreifen. Finde das unter Umständen schon sehr schwierig und ich will das rechtlich nicht verantworten. Wie hoch ist der Aufwand für den Umbau? Vielleicht doch die Daten dann in der Datenbank speichern, so dass es immer eine Fallbacklösung gibt?

**Comment by fritzmg** [comment]
> Finde das unter Umständen schon sehr schwierig und ich will das rechtlich nicht verantworten.

Aber willst du rechtlich verantworten, dass du weiterhin eine Datenschutzerklärung zeigst, die eigentlich veraltet oder nicht mehr zulässig ist?

**Comment by fritzmg** [comment]
Datenbank Fallback ist nun implementiert.

**Comment by fenepedia** [comment]
Tests waren erfolgreich. Vielen Dank.
