### ISSUE TITLE
Paket nicht im Contao-Manager gefunden

### ISSUE THREAD

**Issue by derastronaut** [fenepedia/contao-er24-rechtstexte#4]
Ahoi,

auf der Doku-Seite (https://www.fenepedia.de/contao-er24-rechtstexte) der Erweiterung steht geschrieben, dass man in der Suche vom Contao-Manager **fenepedia/contao-er24-rechtstexte** eingeben soll. Damit lässt sich die Erweiterung leider nicht finden. Auch andere Schreibweisen führen nicht zum Erfolg. Gebe ich nur "fenepedia" ein, wird eine andere Erweiterung (Contao KlickTipp Gateway) gelistet.

CM-Version: 1.5.5
Contao: 4.13.4

Gruß
Sebastian

**Comment by fenepedia** [comment]
Wie von @fritzmg geschrieben, fehlt noch eine Freigabe von eRecht24. Sobald diese vorliegt, werden wir die Erweiterung offiziell verfügbar machen.
