### ISSUE TITLE
User collation ascii_bin on tl_page fields as well

### ISSUE THREAD

**Issue by ben-eSM** [fenepedia/contao-er24-rechtstexte#6]
I just ran into the mysql row size issue when trying to install the extension for a client project. I've noticed that the dca field in tl_content is using the `'customSchemaOptions'=>array('collation'=>'ascii_bin')`, while the fields in tl_page aren't. Haven't tested it yet, but adding the collation to tl_page fields as well might help if someone is close to running into that MySQL restriction.

Nonetheless, thumbs up for this great extension! :)

**Comment by fritzmg** [comment]
That's because these fields depend on an external service and thus we cannot be certain about the content, at least in principle.

You can of course still adjust the collation in your application.

**Comment by fenepedia** [comment]
@ben-eSM 
Could we close this ticket?

**Comment by ben-eSM** [comment]
Sorry for my late reply. You can and you did already close it. :-)
