### ISSUE TITLE
Not able to activate second website root

### ISSUE THREAD

**Issue by lv-der** [fenepedia/contao-er24-rechtstexte#9]
Today I've installed the plugin, generated the API key and set up everything as the helpful setup video told me to. It worked like a charm for the first page root.
Our company uses a Contao installation with two website roots that mirror the whole website (german and english version) together with terminal42's changelanguage plugin. When I try to enter the API key in the second (english) website root and click on save, I get the following error message:

> A client with the URL https://www.domain.tld/_er24/push already exists.

Am I doing something wrong here?
Thanks for your time and efforts in developing the plugin so far!

**Comment by fenepedia** [comment]
You only have to enter the API key once for the main language. If the page tree is not German, the English language will be used automatically.
Provided that the text was also created in English via the eRecht24 Project Manager.

**Comment by lv-der** [comment]
Okay, now after setting a new API key in the english website root (which is the main language), it seems to work. Having to enter the API key in the website root element made me think it has to be done per root. Maybe it would useful to clarify this in the documentation.

Thanks for the fast response!

**Comment by fritzmg** [comment]
Hm, I guess we should remove 

https://github.com/fenepedia/contao-er24-rechtstexte/blob/0ac995f1e052c1d643981d738801f9b0d412a963/contao/dca/tl_page.php#L50

if it really works with only the fallback root.
